# Generated by Django 4.1 on 2022-10-01 16:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
