# Generated by Django 4.1 on 2022-10-02 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_ordercheckout_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator(message='Incorrect email', regex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")]),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Incorrect phone number (xxx xxx xxxx)', regex='^(\\d{3}[- .]?){2}\\d{4}$')]),
        ),
    ]
