# Generated by Django 4.1 on 2022-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('id',)},
        ),
    ]
